site_name: Gaming PC Troubleshooting Guide
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
  - scheme: slate
    primary: orange
    accent: deep orange
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  - scheme: default
    primary: blue
    accent: indigo
    toggle:
      icon: material/white-balance-sunny
      name: Switch to dark mode



extra_css:
  - stylesheets/extra.css